In [ ]:
## Importing packages

# This R environment comes with all of CRAN and many other helpful packages preinstalled.
# You can see which packages are installed by checking out the kaggle/rstats docker image: 
# https://github.com/kaggle/docker-rstats

library(tidyverse) # metapackage with lots of helpful functions

## Running code

# In a notebook, you can run a single code cell by clicking in the cell and then hitting 
# the blue arrow to the left, or by clicking in the cell and pressing Shift+Enter. In a script, 
# you can run code by highlighting the code you want to run and then clicking the blue arrow
# at the bottom of this window.

## Reading in files

# You can access files from datasets you've added to this kernel in the "../input/" directory.
# You can see the files added to this kernel by running the code below. 

list.files(path = "../input")

## Saving data

# If you save any files or images, these will be put in the "output" directory. You 
# can see the output directory by committing and running your kernel (using the 
# Commit & Run button) and then checking out the compiled version of your kernel.

In [1]:
#Example: Sort a Vector
x<- c(7,1,8,3,2,6,5,2,2,4)
x

 [1] 7 1 8 3 2 6 5 2 2 4

In [2]:
sort(x)

 [1] 1 2 2 2 3 4 5 6 7 8

In [3]:
#sort in descending order
sort(x, decreasing=TRUE)

 [1] 8 7 6 5 4 3 2 2 2 1

In [5]:
#vector x remains unaffected
x

 [1] 7 1 8 3 2 6 5 2 2 4

In [6]:
#Print the given vector
x <- c(7,1,8,3,2,6,5,2,2,4)
x
#sort in ascending order
x <- sort(x)
#print the sorted array
x

 [1] 7 1 8 3 2 6 5 2 2 4

 [1] 1 2 2 2 3 4 5 6 7 8

### mtcars dataset

# Print first few rows of the dataset mtcars
head(mtcars) #head function prints first six rows by default

In [8]:
# Print first 8 rows of the dataset mtcars
head(mtcars,8) # prints first eight rows

                  mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag     21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4
Datsun 710        22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1
Hornet 4 Drive    21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1
Hornet Sportabout 18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2
Valiant           18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1
Duster 360        14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4
Merc 240D         24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2

In [9]:
tail(mtcars,10)

                 mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
AMC Javelin      15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2
Camaro Z28       13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4
Pontiac Firebird 19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2
Fiat X1-9        27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1
Porsche 914-2    26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2
Lotus Europa     30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2
Ford Pantera L   15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4
Ferrari Dino     19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6
Maserati Bora    15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8
Volvo 142E       21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2

In [10]:
# Print the class of the data mtcars
class(mtcars)

[1] "data.frame"

In [11]:
str(mtcars)

'data.frame':	32 obs. of  11 variables:
 $ mpg : num  21 21 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 ...
 $ cyl : num  6 6 4 6 8 6 8 4 4 6 ...
 $ disp: num  160 160 108 258 360 ...
 $ hp  : num  110 110 93 110 175 105 245 62 95 123 ...
 $ drat: num  3.9 3.9 3.85 3.08 3.15 2.76 3.21 3.69 3.92 3.92 ...
 $ wt  : num  2.62 2.88 2.32 3.21 3.44 ...
 $ qsec: num  16.5 17 18.6 19.4 17 ...
 $ vs  : num  0 0 1 1 0 1 0 1 1 1 ...
 $ am  : num  1 1 1 0 0 0 0 0 0 0 ...
 $ gear: num  4 4 4 3 3 3 3 4 4 4 ...
 $ carb: num  4 4 1 1 2 1 4 2 2 4 ...

In [12]:
summary(mtcars)

      mpg             cyl             disp             hp
 Min.   :10.40   Min.   :4.000   Min.   : 71.1   Min.   : 52.0
 1st Qu.:15.43   1st Qu.:4.000   1st Qu.:120.8   1st Qu.: 96.5
 Median :19.20   Median :6.000   Median :196.3   Median :123.0
 Mean   :20.09   Mean   :6.188   Mean   :230.7   Mean   :146.7
 3rd Qu.:22.80   3rd Qu.:8.000   3rd Qu.:326.0   3rd Qu.:180.0
 Max.   :33.90   Max.   :8.000   Max.   :472.0   Max.   :335.0
      drat             wt             qsec             vs
 Min.   :2.760   Min.   :1.513   Min.   :14.50   Min.   :0.0000
 1st Qu.:3.080   1st Qu.:2.581   1st Qu.:16.89   1st Qu.:0.0000
 Median :3.695   Median :3.325   Median :17.71   Median :0.0000
 Mean   :3.597   Mean   :3.217   Mean   :17.85   Mean   :0.4375
 3rd Qu.:3.920   3rd Qu.:3.610   3rd Qu.:18.90   3rd Qu.:1.0000
 Max.   :4.930   Max.   :5.424   Max.   :22.90   Max.   :1.0000
       am              gear            carb
 Min.   :0.0000   Min.   :3.000   Min.   :1.000
 1st Qu.:0.0000   1st Qu.:3.000   1st Qu.:2.000
 Median :0.0000   Median :4.000   Median :2.000
 Mean   :0.4062   Mean   :3.688   Mean   :2.812
 3rd Qu.:1.0000   3rd Qu.:4.000   3rd Qu.:4.000
 Max.   :1.0000   Max.   :5.000   Max.   :8.000

In [13]:
# Make a copy of mtcars dataset
mtc <- head(mtcars)
mtc

                  mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1

In [14]:
# Print first row of the dataframe mtc
mtc[1,]

          mpg cyl disp hp  drat wt   qsec  vs am gear carb
Mazda RX4 21  6   160  110 3.9  2.62 16.46 0  1  4    4

In [15]:
# Print Fifth row of the dataframe mtc
mtc[5,]

                  mpg  cyl disp hp  drat wt   qsec  vs am gear carb
Hornet Sportabout 18.7 8   360  175 3.15 3.44 17.02 0  0  3    2

In [16]:
# Print second column of the dataframe mtc
mtc[,2] # method-1

[1] 6 6 4 6 8 6

In [17]:
# Print the second column of the dataframe mtc
mtc$cyl # method 2

[1] 6 6 4 6 8 6

In [19]:
# Print 6th Column of the dataframe
mtc[,6]

[1] 2.620 2.875 2.320 3.215 3.440 3.460

In [20]:
# Print First Three rows of the dataframe mtc
mtc[1:3,]

              mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4     21.0 6   160  110 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag 21.0 6   160  110 3.90 2.875 17.02 0  1  4    4
Datsun 710    22.8 4   108   93 3.85 2.320 18.61 1  1  4    1

In [21]:
# Print columns 3 to 6 of the dataframe
mtc[,3:6]

                  disp hp  drat wt
Mazda RX4         160  110 3.90 2.620
Mazda RX4 Wag     160  110 3.90 2.875
Datsun 710        108   93 3.85 2.320
Hornet 4 Drive    258  110 3.08 3.215
Hornet Sportabout 360  175 3.15 3.440
Valiant           225  105 2.76 3.460

In [22]:
# Print the rows 1,3 and 4
mtc[c(1,3,4),]

               mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4      21.0 6   160  110 3.90 2.620 16.46 0  1  4    4
Datsun 710     22.8 4   108   93 3.85 2.320 18.61 1  1  4    1
Hornet 4 Drive 21.4 6   258  110 3.08 3.215 19.44 1  0  3    1

In [23]:
# Print the columns 2,3,5,7
mtc[,c(2,3,5,7)]

                  cyl disp drat qsec
Mazda RX4         6   160  3.90 16.46
Mazda RX4 Wag     6   160  3.90 17.02
Datsun 710        4   108  3.85 18.61
Hornet 4 Drive    6   258  3.08 19.44
Hornet Sportabout 8   360  3.15 17.02
Valiant           6   225  2.76 20.22